FROM --platform=linux/amd64 node:16.20.2-alpine

ARG ENV_FILE
WORKDIR /backend
COPY backend/package.json backend/yarn.lock backend/.env ./
RUN yarn install

COPY backend .
RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start" ]